apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-0
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE2
            - name: P2P_PORT
              value: '5003'
            - name: HTTP_PORT
              value: '3003'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[5,4,6,2]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
          ports:
            - containerPort: 3003
            - containerPort: 5003
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5003
          targetPort: 5003
        - name: http
          protocol: TCP
          port: 3003
          targetPort: 3003
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-1
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE4
            - name: P2P_PORT
              value: '5005'
            - name: HTTP_PORT
              value: '3005'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[5,4,6,2]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-2.p2p-server:5003
          ports:
            - containerPort: 3005
            - containerPort: 5005
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5005
          targetPort: 5005
        - name: http
          protocol: TCP
          port: 3005
          targetPort: 3005
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-2
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE5
            - name: P2P_PORT
              value: '5006'
            - name: HTTP_PORT
              value: '3006'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[5,4,6,2]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-4.p2p-server:5005,ws://p2p-server-2.p2p-server:5003
          ports:
            - containerPort: 3006
            - containerPort: 5006
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5006
          targetPort: 5006
        - name: http
          protocol: TCP
          port: 3006
          targetPort: 3006
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-3
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE6
            - name: P2P_PORT
              value: '5007'
            - name: HTTP_PORT
              value: '3007'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[5,4,6,2]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-5.p2p-server:5006,ws://p2p-server-4.p2p-server:5005,ws://p2p-server-2.p2p-server:5003
          ports:
            - containerPort: 3007
            - containerPort: 5007
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5007
          targetPort: 5007
        - name: http
          protocol: TCP
          port: 3007
          targetPort: 3007
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-4
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE0
            - name: P2P_PORT
              value: '5001'
            - name: HTTP_PORT
              value: '3001'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[0,3,1,7]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
          ports:
            - containerPort: 3001
            - containerPort: 5001
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5001
          targetPort: 5001
        - name: http
          protocol: TCP
          port: 3001
          targetPort: 3001
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-5
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE1
            - name: P2P_PORT
              value: '5002'
            - name: HTTP_PORT
              value: '3002'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[0,3,1,7]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-0.p2p-server:5001
          ports:
            - containerPort: 3002
            - containerPort: 5002
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5002
          targetPort: 5002
        - name: http
          protocol: TCP
          port: 3002
          targetPort: 3002
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-6
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE3
            - name: P2P_PORT
              value: '5004'
            - name: HTTP_PORT
              value: '3004'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[0,3,1,7]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-0.p2p-server:5001,ws://p2p-server-1.p2p-server:5002
          ports:
            - containerPort: 3004
            - containerPort: 5004
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5004
          targetPort: 5004
        - name: http
          protocol: TCP
          port: 3004
          targetPort: 3004
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-7
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE7
            - name: P2P_PORT
              value: '5008'
            - name: HTTP_PORT
              value: '3008'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[0,3,1,7]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-0.p2p-server:5001,ws://p2p-server-3.p2p-server:5004,ws://p2p-server-1.p2p-server:5002
          ports:
            - containerPort: 3008
            - containerPort: 5008
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: p2p-server
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      clusterIP: None
      selector:
        app: p2p-server
      ports:
        - name: ws
          protocol: TCP
          port: 5008
          targetPort: 5008
        - name: http
          protocol: TCP
          port: 3008
          targetPort: 3008
  - apiVersion: v1
    kind: Pod
    metadata:
      name: core-server
      labels:
        app: core-server
        domain: blockchain
    spec:
      containers:
        - name: core-server
          image: lebaz20/blockchain-core-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - containerPort: 4999
      restartPolicy: Never
  - apiVersion: v1
    kind: Service
    metadata:
      name: core-server
      labels:
        app: core-server
        domain: blockchain
    spec:
      selector:
        app: core-server
      ports:
        - protocol: TCP
          port: 4999
          targetPort: 4999
