apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-0
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE2
            - name: P2P_PORT
              value: '5003'
            - name: HTTP_PORT
              value: '3003'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[4,2,3,7]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
          ports:
            - containerPort: 3003
            - containerPort: 5003
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-1
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE3
            - name: P2P_PORT
              value: '5004'
            - name: HTTP_PORT
              value: '3004'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[4,2,3,7]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-2:5003
          ports:
            - containerPort: 3004
            - containerPort: 5004
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-2
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE4
            - name: P2P_PORT
              value: '5005'
            - name: HTTP_PORT
              value: '3005'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[4,2,3,7]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-2:5003,ws://p2p-server-3:5004
          ports:
            - containerPort: 3005
            - containerPort: 5005
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-3
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE7
            - name: P2P_PORT
              value: '5008'
            - name: HTTP_PORT
              value: '3008'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[4,2,3,7]'
            - name: SUBSET_INDEX
              value: SUBSET1
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-4:5005,ws://p2p-server-2:5003,ws://p2p-server-3:5004
          ports:
            - containerPort: 3008
            - containerPort: 5008
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-4
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE0
            - name: P2P_PORT
              value: '5001'
            - name: HTTP_PORT
              value: '3001'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[1,5,6,0]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
          ports:
            - containerPort: 3001
            - containerPort: 5001
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-5
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE1
            - name: P2P_PORT
              value: '5002'
            - name: HTTP_PORT
              value: '3002'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[1,5,6,0]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-0:5001
          ports:
            - containerPort: 3002
            - containerPort: 5002
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-6
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE5
            - name: P2P_PORT
              value: '5006'
            - name: HTTP_PORT
              value: '3006'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[1,5,6,0]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: ws://p2p-server-1:5002,ws://p2p-server-0:5001
          ports:
            - containerPort: 3006
            - containerPort: 5006
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: p2p-server-7
      labels:
        app: p2p-server
        domain: blockchain
    spec:
      containers:
        - name: p2p-server
          image: lebaz20/blockchain-p2p-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: SECRET
              value: NODE6
            - name: P2P_PORT
              value: '5007'
            - name: HTTP_PORT
              value: '3007'
            - name: TRANSACTION_THRESHOLD
              value: '100'
            - name: NUMBER_OF_NODES
              value: '4'
            - name: NODES_SUBSET
              value: '[1,5,6,0]'
            - name: SUBSET_INDEX
              value: SUBSET2
            - name: CORE
              value: ws://core-server:4999
            - name: PEERS
              value: >-
                ws://p2p-server-1:5002,ws://p2p-server-5:5006,ws://p2p-server-0:5001
          ports:
            - containerPort: 3007
            - containerPort: 5007
      restartPolicy: Never
  - apiVersion: v1
    kind: Pod
    metadata:
      name: core-server
      labels:
        app: core-server
        domain: blockchain
    spec:
      containers:
        - name: core-server
          image: lebaz20/blockchain-core-server:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - containerPort: 4999
      restartPolicy: Never
