/**
 * Timeout constants for consensus protocol operations
 * All values in milliseconds
 */
module.exports = {
  BLOCK_CREATION_TIMEOUT_MS: 10000,
  TRANSACTION_INACTIVITY_THRESHOLD_MS: 8000,
  TRANSACTION_REASSIGNMENT_TIMEOUT_MS: 120000,
  RATE_BROADCAST_INTERVAL_MS: 60000,
  PEER_RECONNECT_DELAY_MS: 5000,
  HEALTH_CHECK_RETRY_MS: 1000
}
